import { Plan } from './types';

export const DEFAULT_PLANS: Plan[] = [
  {
    _id: '6aa3c900e4017433da625f4e',
    name: 'Starter Plan',
    slug: 'starter',
    price: 59,
    currency: 'INR',
    description: 'Essential access to foundational business PDFs and stock market cheat sheets.',
    features: [
      'Access to Essential Business Model PDFs',
      'Stock Market Basics Cheat Sheets',
      'Full Web Reader Access',
      'Standard Resolution Charts & Figures',
      'Lifetime Revisions for Downloaded PDFs',
    ],
    badge: 'Basic Tier',
    popular: false,
    active: true,
    order: 1,
  },
  {
    _id: '6aa3c900e4017433da625f4f',
    name: 'Growth Plan',
    slug: 'growth',
    price: 99,
    currency: 'INR',
    description: 'Comprehensive access to all business PDFs, corporate case studies, and checklists.',
    features: [
      'Complete Library of All Business PDFs',
      'In-Depth Corporate Case Study Autopsies',
      'Forensic Accounting & Ratio Checklists',
      'Downloadable CSV Valuation Datasets',
      'Priority Email Delivery of New Reports',
      'Early Access to Upcoming Publications',
    ],
    badge: 'Most Popular',
    popular: true,
    active: true,
    order: 2,
  },
  {
    _id: '6aa3c900e4017433da625f50',
    name: 'Premium Plan',
    slug: 'premium',
    price: 149,
    currency: 'INR',
    description: 'All-inclusive institutional intelligence suite including 3-statement dynamic Excel financial models.',
    features: [
      'All-Access Pass (PDFs + Excel Models + Video Lessons)',
      'Dynamic 3-Statement Institutional DCF Models (.xlsx)',
      'Full Scenario Sensitivity Tables & Debt Sweeps',
      'Technical Price Action Candlestick Masterclasses',
      'Direct Curriculum Editorial Q&A Privileges',
      'Unrestricted Commercial & Personal Usage',
    ],
    badge: 'Institutional All-Access',
    popular: false,
    active: true,
    order: 3,
  },
];
